# -*- coding: utf-8 -*-

# Developer UI runtime skeleton.
# This module is intentionally checked in as the single UI structure source for
# `developer_frontend.py` (the legacy `.ui` source file is no longer used).


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1946, 1234)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 111, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 111, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(31, 111, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("selection-background-color: #1f6feb;\n"
"selection-color: #ffffff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(12, 622, 531, 600))
        self.frame.setStyleSheet("QFrame#frame { background: #ffffff; border: 1px solid #000000; border-radius: 6px; }")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.yolo_view = QtWidgets.QLabel(self.frame)
        self.yolo_view.setGeometry(QtCore.QRect(10, 93, 511, 341))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.yolo_view.setFont(font)
        self.yolo_view.setFrameShape(QtWidgets.QFrame.Box)
        self.yolo_view.setAlignment(QtCore.Qt.AlignCenter)
        self.yolo_view.setObjectName("yolo_view")
        self.vision_coord_label = QtWidgets.QLabel(self.frame)
        self.vision_coord_label.setGeometry(QtCore.QRect(10, 50, 511, 20))
        self.vision_coord_label.setVisible(False)
        self.vision_coord_label.setText("")
        self.vision_coord_label.setObjectName("vision_coord_label")
        self.vision_cycle_label = QtWidgets.QLabel(self.frame)
        self.vision_cycle_label.setGeometry(QtCore.QRect(330, 36, 168, 14))
        self.vision_cycle_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vision_cycle_label.setObjectName("vision_cycle_label")
        self.vision_serial_label = QtWidgets.QLabel(self.frame)
        self.vision_serial_label.setGeometry(QtCore.QRect(278, 50, 220, 14))
        self.vision_serial_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vision_serial_label.setObjectName("vision_serial_label")
        self.vision_rotate_left_button = QtWidgets.QPushButton(self.frame)
        self.vision_rotate_left_button.setGeometry(QtCore.QRect(10, 70, 44, 20))
        self.vision_rotate_left_button.setObjectName("vision_rotate_left_button")
        self.vision_rotate_zero_button = QtWidgets.QPushButton(self.frame)
        self.vision_rotate_zero_button.setGeometry(QtCore.QRect(58, 70, 44, 20))
        self.vision_rotate_zero_button.setObjectName("vision_rotate_zero_button")
        self.vision_rotate_right_button = QtWidgets.QPushButton(self.frame)
        self.vision_rotate_right_button.setGeometry(QtCore.QRect(106, 70, 44, 20))
        self.vision_rotate_right_button.setObjectName("vision_rotate_right_button")
        self.vision_rotation_label = QtWidgets.QLabel(self.frame)
        self.vision_rotation_label.setGeometry(QtCore.QRect(156, 76, 72, 14))
        self.vision_rotation_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vision_rotation_label.setObjectName("vision_rotation_label")
        self.vision_serial_change_button = QtWidgets.QPushButton(self.frame)
        self.vision_serial_change_button.setGeometry(QtCore.QRect(413, 70, 88, 20))
        self.vision_serial_change_button.setObjectName("vision_serial_change_button")
        self.top_status_vision_dot = QtWidgets.QLabel(self.frame)
        self.top_status_vision_dot.setGeometry(QtCore.QRect(0, 30, 41, 41))
        self.top_status_vision_dot.setAlignment(QtCore.Qt.AlignCenter)
        self.top_status_vision_dot.setObjectName("top_status_vision_dot")
        self.top_status_vision_text = QtWidgets.QLabel(self.frame)
        self.top_status_vision_text.setGeometry(QtCore.QRect(50, 20, 371, 61))
        self.top_status_vision_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.top_status_vision_text.setObjectName("top_status_vision_text")
        self.top_status_vision_toggle = QtWidgets.QCheckBox(self.frame)
        self.top_status_vision_toggle.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.top_status_vision_toggle.setStyleSheet("QCheckBox { font-size: 8pt; font-weight: 700; color: #425466; }QCheckBox::indicator { width: 30px; height: 16px; border-radius: 8px; border: 1px solid #90a4ae; background: #cfd8dc; }QCheckBox::indicator:checked { background: #66bb6a; border: 1px solid #388e3c; }QCheckBox::indicator:unchecked { background: #cfd8dc; border: 1px solid #90a4ae; }")
        self.top_status_vision_toggle.setObjectName("top_status_vision_toggle")
        self.calibration_group_box = QtWidgets.QFrame(self.frame)
        self.calibration_group_box.setGeometry(QtCore.QRect(10, 442, 511, 129))
        self.calibration_group_box.setStyleSheet("QFrame#calibration_group_box { background: #fffdf1; border: 1px solid #d7cf9a; border-radius: 6px; }")
        self.calibration_group_box.setObjectName("calibration_group_box")
        self.calibration_mode_switch = QtWidgets.QCheckBox(self.calibration_group_box)
        self.calibration_mode_switch.setGeometry(QtCore.QRect(14, 8, 281, 41))
        self.calibration_mode_switch.setStyleSheet("QCheckBox#calibration_mode_switch {color: #5f5a1e; font-size: 11.0pt; font-weight: 700; spacing: 10px;}QCheckBox#calibration_mode_switch::indicator { width: 40px; height: 20px; border-radius: 10px; border: 1px solid #b8af71; background: #ede8c8; }QCheckBox#calibration_mode_switch::indicator:checked { background: #2e7d32; border: 1px solid #2e7d32; }")
        self.calibration_mode_switch.setObjectName("calibration_mode_switch")
        self.calibration_status_label = QtWidgets.QLabel(self.calibration_group_box)
        self.calibration_status_label.setGeometry(QtCore.QRect(14, 36, 462, 20))
        self.calibration_status_label.setStyleSheet("color: #5f5a1e; font-size: 9pt; font-weight: 700;")
        self.calibration_status_label.setText("")
        self.calibration_status_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.calibration_status_label.setObjectName("calibration_status_label")
        self.calibration_matrix_file_label = QtWidgets.QLabel(self.calibration_group_box)
        self.calibration_matrix_file_label.setGeometry(QtCore.QRect(14, 56, 376, 22))
        self.calibration_matrix_file_label.setStyleSheet("color: #666666; font-size: 8pt;")
        self.calibration_matrix_file_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.calibration_matrix_file_label.setObjectName("calibration_matrix_file_label")
        self.calibration_load_button = QtWidgets.QPushButton(self.calibration_group_box)
        self.calibration_load_button.setGeometry(QtCore.QRect(394, 54, 82, 26))
        self.calibration_load_button.setVisible(False)
        self.calibration_load_button.setObjectName("calibration_load_button")
        self.calibration_transform_button = QtWidgets.QPushButton(self.calibration_group_box)
        self.calibration_transform_button.setGeometry(QtCore.QRect(14, 86, 462, 32))
        self.calibration_transform_button.setVisible(False)
        self.calibration_transform_button.setObjectName("calibration_transform_button")
        self.voice_order_panel = QtWidgets.QFrame(self.centralwidget)
        self.voice_order_panel.setGeometry(QtCore.QRect(12, 12, 531, 600))
        self.voice_order_panel.setStyleSheet("QFrame#voice_order_panel { background: #ffffff; border: 1px solid #000000; border-radius: 6px; }")
        self.voice_order_panel.setFrameShape(QtWidgets.QFrame.Box)
        self.voice_order_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.voice_order_panel.setObjectName("voice_order_panel")
        self.voice_order_connection_toggle = QtWidgets.QCheckBox(self.voice_order_panel)
        self.voice_order_connection_toggle.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.voice_order_connection_toggle.setStyleSheet("QCheckBox { font-size: 8pt; font-weight: 700; color: #425466; }QCheckBox::indicator { width: 30px; height: 16px; border-radius: 8px; border: 1px solid #90a4ae; background: #cfd8dc; }QCheckBox::indicator:checked { background: #66bb6a; border: 1px solid #388e3c; }QCheckBox::indicator:unchecked { background: #cfd8dc; border: 1px solid #90a4ae; }")
        self.voice_order_connection_toggle.setObjectName("voice_order_connection_toggle")
        self.voice_order_cycle_label = QtWidgets.QLabel(self.voice_order_panel)
        self.voice_order_cycle_label.setGeometry(QtCore.QRect(353, 10, 168, 16))
        self.voice_order_cycle_label.setStyleSheet("font-size: 9pt; color: #555555;")
        self.voice_order_cycle_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.voice_order_cycle_label.setObjectName("voice_order_cycle_label")
        self.voice_order_connection_dot = QtWidgets.QLabel(self.voice_order_panel)
        self.voice_order_connection_dot.setGeometry(QtCore.QRect(0, 36, 41, 41))
        self.voice_order_connection_dot.setStyleSheet("font-size: 20pt; color: #EF6C00;")
        self.voice_order_connection_dot.setAlignment(QtCore.Qt.AlignCenter)
        self.voice_order_connection_dot.setObjectName("voice_order_connection_dot")
        self.voice_order_connection_label = QtWidgets.QLabel(self.voice_order_panel)
        self.voice_order_connection_label.setGeometry(QtCore.QRect(50, 26, 351, 61))
        self.voice_order_connection_label.setStyleSheet("font-size: 14pt; font-weight: 700; color: #202020;")
        self.voice_order_connection_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.voice_order_connection_label.setObjectName("voice_order_connection_label")
        self.voice_order_input_label = QtWidgets.QLabel(self.voice_order_panel)
        self.voice_order_input_label.setGeometry(QtCore.QRect(10, 90, 511, 20))
        self.voice_order_input_label.setStyleSheet("font-size: 10pt; font-weight: 600; color: #1f2937;")
        self.voice_order_input_label.setObjectName("voice_order_input_label")
        self.voice_order_input_edit = QtWidgets.QPlainTextEdit(self.voice_order_panel)
        self.voice_order_input_edit.setGeometry(QtCore.QRect(10, 112, 511, 78))
        self.voice_order_input_edit.setStyleSheet("QPlainTextEdit { background: #f8fafc; color: #0f172a; border: 1px solid #cbd5e1; border-radius: 4px; padding: 6px; }")
        self.voice_order_input_edit.setObjectName("voice_order_input_edit")
        self.voice_order_llm_label = QtWidgets.QLabel(self.voice_order_panel)
        self.voice_order_llm_label.setGeometry(QtCore.QRect(10, 198, 511, 20))
        self.voice_order_llm_label.setStyleSheet("font-size: 10pt; font-weight: 600; color: #1f2937;")
        self.voice_order_llm_label.setObjectName("voice_order_llm_label")
        self.voice_order_llm_edit = QtWidgets.QPlainTextEdit(self.voice_order_panel)
        self.voice_order_llm_edit.setGeometry(QtCore.QRect(10, 220, 511, 60))
        self.voice_order_llm_edit.setStyleSheet("QPlainTextEdit { background: #f8fafc; color: #0f172a; border: 1px solid #cbd5e1; border-radius: 4px; padding: 6px; }")
        self.voice_order_llm_edit.setObjectName("voice_order_llm_edit")
        self.voice_order_mic_button = QtWidgets.QPushButton(self.voice_order_panel)
        self.voice_order_mic_button.setGeometry(QtCore.QRect(10, 288, 511, 28))
        self.voice_order_mic_button.setStyleSheet("QPushButton { background: #1f6feb; color: #ffffff; border: 1px solid #1f6feb; border-radius: 4px; font-weight: 700; }QPushButton:hover { background: #1660ce; }QPushButton:disabled { background: #94a3b8; border-color: #94a3b8; color: #f8fafc; }")
        self.voice_order_mic_button.setObjectName("voice_order_mic_button")
        self.voice_order_mic_state_label = QtWidgets.QLabel(self.voice_order_panel)
        self.voice_order_mic_state_label.setGeometry(QtCore.QRect(10, 322, 511, 18))
        self.voice_order_mic_state_label.setStyleSheet("font-size: 9.2pt; font-weight: 700; color: #1f2937;")
        self.voice_order_mic_state_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.voice_order_mic_state_label.setObjectName("voice_order_mic_state_label")
        self.voice_order_log_label = QtWidgets.QLabel(self.voice_order_panel)
        self.voice_order_log_label.setGeometry(QtCore.QRect(10, 324, 511, 20))
        self.voice_order_log_label.setVisible(False)
        self.voice_order_log_label.setStyleSheet("font-size: 10pt; font-weight: 600; color: #1f2937;")
        self.voice_order_log_label.setObjectName("voice_order_log_label")
        self.voice_order_log_view = QtWidgets.QPlainTextEdit(self.voice_order_panel)
        self.voice_order_log_view.setGeometry(QtCore.QRect(10, 346, 511, 180))
        self.voice_order_log_view.setVisible(False)
        self.voice_order_log_view.setStyleSheet("QPlainTextEdit { background: #0f172a; color: #dbeafe; border: 1px solid #334155; border-radius: 4px; }")
        self.voice_order_log_view.setObjectName("voice_order_log_view")
        self.voice_order_result_label = QtWidgets.QLabel(self.voice_order_panel)
        self.voice_order_result_label.setGeometry(QtCore.QRect(10, 324, 511, 20))
        self.voice_order_result_label.setStyleSheet("font-size: 10pt; font-weight: 600; color: #1f2937;")
        self.voice_order_result_label.setObjectName("voice_order_result_label")
        self.voice_order_recipe_view = QtWidgets.QPlainTextEdit(self.voice_order_panel)
        self.voice_order_recipe_view.setGeometry(QtCore.QRect(10, 346, 511, 178))
        self.voice_order_recipe_view.setStyleSheet("QPlainTextEdit { background: #f8fafc; color: #0f172a; border: 1px solid #cbd5e1; border-radius: 4px; }")
        self.voice_order_recipe_view.setObjectName("voice_order_recipe_view")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(553, 12, 531, 600))
        self.frame_2.setStyleSheet("QFrame#frame_2 { background: #ffffff; border: 1px solid #000000; border-radius: 6px; }")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.c_value = QtWidgets.QLabel(self.frame_2)
        self.c_value.setGeometry(QtCore.QRect(250, 205, 140, 20))
        self.c_value.setObjectName("c_value")
        self.j5_value = QtWidgets.QLabel(self.frame_2)
        self.j5_value.setGeometry(QtCore.QRect(65, 180, 120, 20))
        self.j5_value.setObjectName("j5_value")
        self.a_label = QtWidgets.QLabel(self.frame_2)
        self.a_label.setGeometry(QtCore.QRect(224, 155, 20, 20))
        self.a_label.setObjectName("a_label")
        self.a_value = QtWidgets.QLabel(self.frame_2)
        self.a_value.setGeometry(QtCore.QRect(250, 155, 140, 20))
        self.a_value.setObjectName("a_value")
        self.y_label = QtWidgets.QLabel(self.frame_2)
        self.y_label.setGeometry(QtCore.QRect(224, 105, 20, 20))
        self.y_label.setObjectName("y_label")
        self.j3_label = QtWidgets.QLabel(self.frame_2)
        self.j3_label.setGeometry(QtCore.QRect(25, 130, 30, 20))
        self.j3_label.setObjectName("j3_label")
        self.y_value = QtWidgets.QLabel(self.frame_2)
        self.y_value.setGeometry(QtCore.QRect(250, 105, 140, 20))
        self.y_value.setObjectName("y_value")
        self.j2_label = QtWidgets.QLabel(self.frame_2)
        self.j2_label.setGeometry(QtCore.QRect(25, 105, 30, 20))
        self.j2_label.setObjectName("j2_label")
        self.j2_value = QtWidgets.QLabel(self.frame_2)
        self.j2_value.setGeometry(QtCore.QRect(65, 105, 120, 20))
        self.j2_value.setObjectName("j2_value")
        self.j4_label = QtWidgets.QLabel(self.frame_2)
        self.j4_label.setGeometry(QtCore.QRect(25, 155, 30, 20))
        self.j4_label.setObjectName("j4_label")
        self.joint_table = QtWidgets.QTableWidget(self.frame_2)
        self.joint_table.setGeometry(QtCore.QRect(11, 100, 150, 195))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.joint_table.setFont(font)
        self.joint_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.joint_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.joint_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.joint_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.joint_table.setWordWrap(False)
        self.joint_table.setRowCount(6)
        self.joint_table.setColumnCount(2)
        self.joint_table.setObjectName("joint_table")
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.joint_table.setItem(5, 1, item)
        self.joint_table.horizontalHeader().setMinimumSectionSize(20)
        self.joint_table.horizontalHeader().setStretchLastSection(True)
        self.joint_table.verticalHeader().setVisible(False)
        self.joint_table.verticalHeader().setDefaultSectionSize(20)
        self.cart_table = QtWidgets.QTableWidget(self.frame_2)
        self.cart_table.setGeometry(QtCore.QRect(171, 100, 161, 195))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cart_table.setFont(font)
        self.cart_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cart_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cart_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.cart_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.cart_table.setWordWrap(False)
        self.cart_table.setRowCount(6)
        self.cart_table.setColumnCount(2)
        self.cart_table.setObjectName("cart_table")
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setItem(5, 1, item)
        self.cart_table.horizontalHeader().setMinimumSectionSize(20)
        self.cart_table.horizontalHeader().setStretchLastSection(True)
        self.cart_table.verticalHeader().setVisible(False)
        self.cart_table.verticalHeader().setDefaultSectionSize(20)
        self.robot_state_table = QtWidgets.QTableWidget(self.frame_2)
        self.robot_state_table.setGeometry(QtCore.QRect(340, 100, 181, 195))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.robot_state_table.setFont(font)
        self.robot_state_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.robot_state_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.robot_state_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.robot_state_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.robot_state_table.setWordWrap(False)
        self.robot_state_table.setRowCount(6)
        self.robot_state_table.setColumnCount(2)
        self.robot_state_table.setObjectName("robot_state_table")
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_state_table.setItem(5, 1, item)
        self.robot_state_table.horizontalHeader().setMinimumSectionSize(20)
        self.robot_state_table.horizontalHeader().setStretchLastSection(True)
        self.robot_state_table.verticalHeader().setVisible(False)
        self.robot_state_table.verticalHeader().setDefaultSectionSize(20)
        self.robot_cycle_label = QtWidgets.QLabel(self.frame_2)
        self.robot_cycle_label.setGeometry(QtCore.QRect(340, 30, 178, 14))
        self.robot_cycle_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.robot_cycle_label.setObjectName("robot_cycle_label")
        self.motion_group_box = QtWidgets.QFrame(self.frame_2)
        self.motion_group_box.setGeometry(QtCore.QRect(10, 300, 511, 131))
        self.motion_group_box.setStyleSheet("QFrame#motion_group_box { background: #f3f8ff; border: 1px solid #a9c3e8; border-radius: 6px; }")
        self.motion_group_box.setObjectName("motion_group_box")
        self.motion_group_title = QtWidgets.QLabel(self.motion_group_box)
        self.motion_group_title.setGeometry(QtCore.QRect(10, 0, 120, 21))
        self.motion_group_title.setStyleSheet("color: #1f3b63; font-size: 9.5pt; font-weight: 700;")
        self.motion_group_title.setObjectName("motion_group_title")
        self.home_button = QtWidgets.QPushButton(self.motion_group_box)
        self.home_button.setGeometry(QtCore.QRect(10, 30, 113, 41))
        self.home_button.setObjectName("home_button")
        self.pushButton = QtWidgets.QPushButton(self.motion_group_box)
        self.pushButton.setGeometry(QtCore.QRect(136, 80, 113, 41))
        self.pushButton.setObjectName("pushButton")
        self.reset_button = QtWidgets.QPushButton(self.motion_group_box)
        self.reset_button.setGeometry(QtCore.QRect(388, 30, 113, 41))
        self.reset_button.setStyleSheet("QPushButton {\n"
"    background-color: #ffeb3b;\n"
"    color: #222222;\n"
"    border: 1px solid #d4b400;\n"
"    border-radius: 4px;\n"
"    padding: 4px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #fff176;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #fbc02d;\n"
"    border: 1px solid #b28704;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #eceff1;\n"
"    color: #9e9e9e;\n"
"    border: 1px solid #cfd8dc;\n"
"}")
        self.reset_button.setObjectName("reset_button")
        self.print_pos_button = QtWidgets.QPushButton(self.motion_group_box)
        self.print_pos_button.setGeometry(QtCore.QRect(136, 30, 113, 41))
        self.print_pos_button.setObjectName("print_pos_button")
        self.print_pos_button_2 = QtWidgets.QPushButton(self.motion_group_box)
        self.print_pos_button_2.setGeometry(QtCore.QRect(262, 30, 113, 41))
        self.print_pos_button_2.setObjectName("print_pos_button_2")
        self.home_button_2 = QtWidgets.QPushButton(self.motion_group_box)
        self.home_button_2.setGeometry(QtCore.QRect(10, 80, 113, 41))
        self.home_button_2.setObjectName("home_button_2")
        self.tool_change_button = QtWidgets.QPushButton(self.motion_group_box)
        self.tool_change_button.setGeometry(QtCore.QRect(262, 80, 113, 41))
        self.tool_change_button.setObjectName("tool_change_button")
        self.emergency_stop_button = QtWidgets.QPushButton(self.motion_group_box)
        self.emergency_stop_button.setGeometry(QtCore.QRect(388, 80, 113, 41))
        self.emergency_stop_button.setStyleSheet("QPushButton {\n"
"    background-color: #d32f2f;\n"
"    color: #ffeb3b;\n"
"    border: 1px solid #9a0007;\n"
"    border-radius: 4px;\n"
"    padding: 4px 10px;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e53935;\n"
"    color: #fff176;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;\n"
"    border: 1px solid #7f0000;\n"
"    color: #fdd835;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #eceff1;\n"
"    color: #9e9e9e;\n"
"    border: 1px solid #cfd8dc;\n"
"}")
        self.emergency_stop_button.setObjectName("emergency_stop_button")
        self.gripper_manual_box = QtWidgets.QFrame(self.frame_2)
        self.gripper_manual_box.setGeometry(QtCore.QRect(320, 440, 201, 131))
        self.gripper_manual_box.setStyleSheet("QFrame#gripper_manual_box { background: #eef5ff; border: 1px solid #9eb9dd; border-radius: 6px; }")
        self.gripper_manual_box.setFrameShape(QtWidgets.QFrame.Box)
        self.gripper_manual_box.setFrameShadow(QtWidgets.QFrame.Plain)
        self.gripper_manual_box.setObjectName("gripper_manual_box")
        self.gripper_move_button = QtWidgets.QPushButton(self.gripper_manual_box)
        self.gripper_move_button.setGeometry(QtCore.QRect(20, 90, 161, 31))
        self.gripper_move_button.setObjectName("gripper_move_button")
        self.gripper_stroke_input = QtWidgets.QLineEdit(self.gripper_manual_box)
        self.gripper_stroke_input.setGeometry(QtCore.QRect(20, 50, 161, 31))
        self.gripper_stroke_input.setMaxLength(6)
        self.gripper_stroke_input.setAlignment(QtCore.Qt.AlignCenter)
        self.gripper_stroke_input.setObjectName("gripper_stroke_input")
        self.gripper_range_value_label = QtWidgets.QLabel(self.gripper_manual_box)
        self.gripper_range_value_label.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.gripper_range_value_label.setStyleSheet("color: #334155; font-size: 8.8pt;")
        self.gripper_range_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gripper_range_value_label.setObjectName("gripper_range_value_label")
        self.gripper_range_title_label = QtWidgets.QLabel(self.gripper_manual_box)
        self.gripper_range_title_label.setGeometry(QtCore.QRect(10, 10, 181, 20))
        self.gripper_range_title_label.setStyleSheet("color: #1f3b63; font-size: 9.5pt; font-weight: 700;")
        self.gripper_range_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gripper_range_title_label.setObjectName("gripper_range_title_label")
        self.vision_group_box = QtWidgets.QFrame(self.frame_2)
        self.vision_group_box.setGeometry(QtCore.QRect(10, 440, 301, 131))
        self.vision_group_box.setStyleSheet("QFrame#vision_group_box { background: #f3fbf4; border: 1px solid #9eccaa; border-radius: 6px; }")
        self.vision_group_box.setObjectName("vision_group_box")
        self.vision_dialog_toggle_switch = QtWidgets.QCheckBox(self.vision_group_box)
        self.vision_dialog_toggle_switch.setGeometry(QtCore.QRect(10, 0, 170, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(88)
        self.vision_dialog_toggle_switch.setFont(font)
        self.vision_dialog_toggle_switch.setStyleSheet("QCheckBox#vision_dialog_toggle_switch {color: #205c2f; font-size: 11.0pt; font-weight: 700;}QCheckBox#vision_dialog_toggle_switch::indicator { width: 40px; height: 20px; border-radius: 10px; border: 1px solid #95a5b4; background: #d6dde5; }QCheckBox#vision_dialog_toggle_switch::indicator:checked { background: #2e7d32; border: 1px solid #2e7d32; }")
        self.vision_dialog_toggle_switch.setObjectName("vision_dialog_toggle_switch")
        self.vision_x_axis_label = QtWidgets.QLabel(self.vision_group_box)
        self.vision_x_axis_label.setGeometry(QtCore.QRect(120, 50, 52, 20))
        self.vision_x_axis_label.setStyleSheet("color: #205c2f; font-size: 9pt; font-weight: 700;")
        self.vision_x_axis_label.setAlignment(QtCore.Qt.AlignCenter)
        self.vision_x_axis_label.setObjectName("vision_x_axis_label")
        self.vision_y_axis_label = QtWidgets.QLabel(self.vision_group_box)
        self.vision_y_axis_label.setGeometry(QtCore.QRect(176, 50, 52, 20))
        self.vision_y_axis_label.setStyleSheet("color: #205c2f; font-size: 9pt; font-weight: 700;")
        self.vision_y_axis_label.setAlignment(QtCore.Qt.AlignCenter)
        self.vision_y_axis_label.setObjectName("vision_y_axis_label")
        self.vision_z_axis_label = QtWidgets.QLabel(self.vision_group_box)
        self.vision_z_axis_label.setGeometry(QtCore.QRect(232, 50, 52, 20))
        self.vision_z_axis_label.setStyleSheet("color: #205c2f; font-size: 9pt; font-weight: 700;")
        self.vision_z_axis_label.setAlignment(QtCore.Qt.AlignCenter)
        self.vision_z_axis_label.setObjectName("vision_z_axis_label")
        self.vision_x_margin_input = QtWidgets.QLineEdit(self.vision_group_box)
        self.vision_x_margin_input.setGeometry(QtCore.QRect(120, 72, 52, 24))
        self.vision_x_margin_input.setMaxLength(7)
        self.vision_x_margin_input.setAlignment(QtCore.Qt.AlignCenter)
        self.vision_x_margin_input.setObjectName("vision_x_margin_input")
        self.vision_y_margin_input = QtWidgets.QLineEdit(self.vision_group_box)
        self.vision_y_margin_input.setGeometry(QtCore.QRect(176, 72, 52, 24))
        self.vision_y_margin_input.setMaxLength(7)
        self.vision_y_margin_input.setAlignment(QtCore.Qt.AlignCenter)
        self.vision_y_margin_input.setObjectName("vision_y_margin_input")
        self.vision_z_margin_input = QtWidgets.QLineEdit(self.vision_group_box)
        self.vision_z_margin_input.setGeometry(QtCore.QRect(232, 72, 52, 24))
        self.vision_z_margin_input.setMaxLength(7)
        self.vision_z_margin_input.setAlignment(QtCore.Qt.AlignCenter)
        self.vision_z_margin_input.setObjectName("vision_z_margin_input")
        self.vision_move_button = QtWidgets.QPushButton(self.vision_group_box)
        self.vision_move_button.setGeometry(QtCore.QRect(180, 98, 111, 24))
        self.vision_move_button.setObjectName("vision_move_button")
        self.vision_z_range_label = QtWidgets.QLabel(self.vision_group_box)
        self.vision_z_range_label.setGeometry(QtCore.QRect(10, 102, 161, 16))
        self.vision_z_range_label.setStyleSheet("color: #334155; font-size: 8.8pt;")
        self.vision_z_range_label.setObjectName("vision_z_range_label")
        self.vision_z_title_label = QtWidgets.QLabel(self.vision_group_box)
        self.vision_z_title_label.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.vision_z_title_label.setStyleSheet("color: #205c2f; font-size: 7.5pt; font-weight: 700;")
        self.vision_z_title_label.setObjectName("vision_z_title_label")
        self.vision_dialog_toggle_button = QtWidgets.QPushButton(self.frame_2)
        self.vision_dialog_toggle_button.setGeometry(QtCore.QRect(26, 406, 170, 30))
        self.vision_dialog_toggle_button.setVisible(False)
        self.vision_dialog_toggle_button.setObjectName("vision_dialog_toggle_button")
        self.top_status_robot_text = QtWidgets.QLabel(self.frame_2)
        self.top_status_robot_text.setGeometry(QtCore.QRect(50, 30, 381, 41))
        self.top_status_robot_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.top_status_robot_text.setObjectName("top_status_robot_text")
        self.top_status_robot_dot = QtWidgets.QLabel(self.frame_2)
        self.top_status_robot_dot.setGeometry(QtCore.QRect(0, 30, 41, 41))
        self.top_status_robot_dot.setAlignment(QtCore.Qt.AlignCenter)
        self.top_status_robot_dot.setObjectName("top_status_robot_dot")
        self.top_status_robot_toggle = QtWidgets.QCheckBox(self.frame_2)
        self.top_status_robot_toggle.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.top_status_robot_toggle.setStyleSheet("QCheckBox { font-size: 8pt; font-weight: 700; color: #425466; }QCheckBox::indicator { width: 30px; height: 16px; border-radius: 8px; border: 1px solid #90a4ae; background: #cfd8dc; }QCheckBox::indicator:checked { background: #66bb6a; border: 1px solid #388e3c; }QCheckBox::indicator:unchecked { background: #cfd8dc; border: 1px solid #90a4ae; }")
        self.top_status_robot_toggle.setObjectName("top_status_robot_toggle")
        self.current_tool_label = QtWidgets.QLabel(self.frame_2)
        self.current_tool_label.setGeometry(QtCore.QRect(10, 70, 321, 31))
        self.current_tool_label.setStyleSheet("color: #555555;")
        self.current_tool_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.current_tool_label.setObjectName("current_tool_label")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(1094, 12, 840, 1210))
        self.frame_3.setStyleSheet("QFrame#frame_3 { background: #ffffff; border: 1px solid #000000\n"
"; border-radius: 6px; }")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.terminal = QtWidgets.QPlainTextEdit(self.frame_3)
        self.terminal.setGeometry(QtCore.QRect(10, 40, 820, 1160))
        self.terminal.setObjectName("terminal")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.log_clear_button = QtWidgets.QPushButton(self.frame_3)
        self.log_clear_button.setGeometry(QtCore.QRect(732, 8, 96, 24))
        self.log_clear_button.setObjectName("log_clear_button")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(553, 622, 531, 600))
        self.frame_4.setStyleSheet("QFrame#frame_4 { background: #ffffff; border: 1px solid #000000; border-radius: 6px; }")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.yolo_view_2 = QtWidgets.QLabel(self.frame_4)
        self.yolo_view_2.setGeometry(QtCore.QRect(10, 93, 511, 341))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.yolo_view_2.setFont(font)
        self.yolo_view_2.setFrameShape(QtWidgets.QFrame.Box)
        self.yolo_view_2.setAlignment(QtCore.Qt.AlignCenter)
        self.yolo_view_2.setObjectName("yolo_view_2")
        self.vision_coord_label_2 = QtWidgets.QLabel(self.frame_4)
        self.vision_coord_label_2.setGeometry(QtCore.QRect(10, 50, 511, 20))
        self.vision_coord_label_2.setVisible(False)
        self.vision_coord_label_2.setText("")
        self.vision_coord_label_2.setObjectName("vision_coord_label_2")
        self.vision_cycle_label_2 = QtWidgets.QLabel(self.frame_4)
        self.vision_cycle_label_2.setGeometry(QtCore.QRect(330, 30, 168, 14))
        self.vision_cycle_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vision_cycle_label_2.setObjectName("vision_cycle_label_2")
        self.vision_serial_label_2 = QtWidgets.QLabel(self.frame_4)
        self.vision_serial_label_2.setGeometry(QtCore.QRect(278, 44, 220, 14))
        self.vision_serial_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vision_serial_label_2.setObjectName("vision_serial_label_2")
        self.vision_rotate_left_button_2 = QtWidgets.QPushButton(self.frame_4)
        self.vision_rotate_left_button_2.setGeometry(QtCore.QRect(10, 70, 44, 20))
        self.vision_rotate_left_button_2.setObjectName("vision_rotate_left_button_2")
        self.vision_rotate_zero_button_2 = QtWidgets.QPushButton(self.frame_4)
        self.vision_rotate_zero_button_2.setGeometry(QtCore.QRect(58, 70, 44, 20))
        self.vision_rotate_zero_button_2.setObjectName("vision_rotate_zero_button_2")
        self.vision_rotate_right_button_2 = QtWidgets.QPushButton(self.frame_4)
        self.vision_rotate_right_button_2.setGeometry(QtCore.QRect(106, 70, 44, 20))
        self.vision_rotate_right_button_2.setObjectName("vision_rotate_right_button_2")
        self.vision_rotation_label_2 = QtWidgets.QLabel(self.frame_4)
        self.vision_rotation_label_2.setGeometry(QtCore.QRect(156, 76, 72, 14))
        self.vision_rotation_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vision_rotation_label_2.setObjectName("vision_rotation_label_2")
        self.vision_serial_change_button_2 = QtWidgets.QPushButton(self.frame_4)
        self.vision_serial_change_button_2.setGeometry(QtCore.QRect(413, 70, 88, 20))
        self.vision_serial_change_button_2.setObjectName("vision_serial_change_button_2")
        self.top_status_vision_dot_2 = QtWidgets.QLabel(self.frame_4)
        self.top_status_vision_dot_2.setGeometry(QtCore.QRect(0, 30, 41, 41))
        self.top_status_vision_dot_2.setAlignment(QtCore.Qt.AlignCenter)
        self.top_status_vision_dot_2.setObjectName("top_status_vision_dot_2")
        self.top_status_vision_text_2 = QtWidgets.QLabel(self.frame_4)
        self.top_status_vision_text_2.setGeometry(QtCore.QRect(50, 20, 371, 61))
        self.top_status_vision_text_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.top_status_vision_text_2.setObjectName("top_status_vision_text_2")
        self.top_status_vision2_toggle = QtWidgets.QCheckBox(self.frame_4)
        self.top_status_vision2_toggle.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.top_status_vision2_toggle.setStyleSheet("QCheckBox { font-size: 8pt; font-weight: 700; color: #425466; }QCheckBox::indicator { width: 30px; height: 16px; border-radius: 8px; border: 1px solid #90a4ae; background: #cfd8dc; }QCheckBox::indicator:checked { background: #66bb6a; border: 1px solid #388e3c; }QCheckBox::indicator:unchecked { background: #cfd8dc; border: 1px solid #90a4ae; }")
        self.top_status_vision2_toggle.setObjectName("top_status_vision2_toggle")
        self.calibration_group_box_2 = QtWidgets.QFrame(self.frame_4)
        self.calibration_group_box_2.setGeometry(QtCore.QRect(10, 442, 511, 129))
        self.calibration_group_box_2.setStyleSheet("QFrame#calibration_group_box_2 { background: #fffdf1; border: 1px solid #d7cf9a; border-radius: 6px; }")
        self.calibration_group_box_2.setObjectName("calibration_group_box_2")
        self.calibration_mode_switch_2 = QtWidgets.QCheckBox(self.calibration_group_box_2)
        self.calibration_mode_switch_2.setGeometry(QtCore.QRect(14, 8, 281, 41))
        self.calibration_mode_switch_2.setStyleSheet("QCheckBox#calibration_mode_switch_2 {color: #5f5a1e; font-size: 11.0pt; font-weight: 700; spacing: 10px;}QCheckBox#calibration_mode_switch_2::indicator { width: 40px; height: 20px; border-radius: 10px; border: 1px solid #b8af71; background: #ede8c8; }QCheckBox#calibration_mode_switch_2::indicator:checked { background: #2e7d32; border: 1px solid #2e7d32; }")
        self.calibration_mode_switch_2.setObjectName("calibration_mode_switch_2")
        self.calibration_status_label_2 = QtWidgets.QLabel(self.calibration_group_box_2)
        self.calibration_status_label_2.setGeometry(QtCore.QRect(14, 36, 462, 20))
        self.calibration_status_label_2.setStyleSheet("color: #5f5a1e; font-size: 9pt; font-weight: 700;")
        self.calibration_status_label_2.setText("")
        self.calibration_status_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.calibration_status_label_2.setObjectName("calibration_status_label_2")
        self.calibration_matrix_file_label_2 = QtWidgets.QLabel(self.calibration_group_box_2)
        self.calibration_matrix_file_label_2.setGeometry(QtCore.QRect(14, 56, 376, 22))
        self.calibration_matrix_file_label_2.setStyleSheet("color: #666666; font-size: 8pt;")
        self.calibration_matrix_file_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.calibration_matrix_file_label_2.setObjectName("calibration_matrix_file_label_2")
        self.calibration_load_button_2 = QtWidgets.QPushButton(self.calibration_group_box_2)
        self.calibration_load_button_2.setGeometry(QtCore.QRect(394, 54, 82, 26))
        self.calibration_load_button_2.setVisible(False)
        self.calibration_load_button_2.setObjectName("calibration_load_button_2")
        self.calibration_transform_button_2 = QtWidgets.QPushButton(self.calibration_group_box_2)
        self.calibration_transform_button_2.setGeometry(QtCore.QRect(14, 86, 462, 32))
        self.calibration_transform_button_2.setVisible(False)
        self.calibration_transform_button_2.setObjectName("calibration_transform_button_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "바텐더 로봇"))
        self.yolo_view.setText(_translate("MainWindow", "YOLO 화면 영역"))
        self.vision_cycle_label.setText(_translate("MainWindow", "업데이트: - ms"))
        self.vision_serial_label.setText(_translate("MainWindow", "시리얼: -"))
        self.vision_rotate_left_button.setText(_translate("MainWindow", "↺90"))
        self.vision_rotate_zero_button.setText(_translate("MainWindow", "0°"))
        self.vision_rotate_right_button.setText(_translate("MainWindow", "↻90"))
        self.vision_rotation_label.setText(_translate("MainWindow", "각도: 0°"))
        self.vision_serial_change_button.setText(_translate("MainWindow", "카메라 변경"))
        self.top_status_vision_dot.setText(_translate("MainWindow", "●"))
        self.top_status_vision_text.setText(_translate("MainWindow", "비전1: 확인중"))
        self.top_status_vision_toggle.setText(_translate("MainWindow", "ON"))
        self.calibration_mode_switch.setText(_translate("MainWindow", "켈리브레이션활성화"))
        self.calibration_matrix_file_label.setText(_translate("MainWindow", "현재 적용행렬 : (없음)"))
        self.calibration_load_button.setText(_translate("MainWindow", "불러오기"))
        self.calibration_transform_button.setText(_translate("MainWindow", "비전<-> 로봇 좌표 켈리브레이션 시작"))
        self.voice_order_connection_toggle.setText(_translate("MainWindow", "OFF"))
        self.voice_order_cycle_label.setText(_translate("MainWindow", "업데이트: - ms"))
        self.voice_order_connection_dot.setText(_translate("MainWindow", "●"))
        self.voice_order_connection_label.setText(_translate("MainWindow", "음성주문: 비활성화"))
        self.voice_order_input_label.setText(_translate("MainWindow", "마이크 입력(STT 결과)"))
        self.voice_order_input_edit.setPlaceholderText(_translate("MainWindow", "노트북 마이크 입력 대기중..."))
        self.voice_order_llm_label.setText(_translate("MainWindow", "LLM 응답(TTS)"))
        self.voice_order_llm_edit.setPlaceholderText(_translate("MainWindow", "음성주문 응답 대기중..."))
        self.voice_order_mic_button.setText(_translate("MainWindow", "마이크 입력 시작"))
        self.voice_order_mic_state_label.setText(_translate("MainWindow", "마이크 상태: 대기"))
        self.voice_order_log_label.setText(_translate("MainWindow", "처리 로그"))
        self.voice_order_result_label.setText(_translate("MainWindow", "도출 결과"))
        self.c_value.setText(_translate("MainWindow", "-"))
        self.j5_value.setText(_translate("MainWindow", "-"))
        self.a_label.setText(_translate("MainWindow", "A"))
        self.a_value.setText(_translate("MainWindow", "-"))
        self.y_label.setText(_translate("MainWindow", "Y"))
        self.j3_label.setText(_translate("MainWindow", "J3"))
        self.y_value.setText(_translate("MainWindow", "-"))
        self.j2_label.setText(_translate("MainWindow", "J2"))
        self.j2_value.setText(_translate("MainWindow", "-"))
        self.j4_label.setText(_translate("MainWindow", "J4"))
        item = self.joint_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "항목"))
        item = self.joint_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "값"))
        __sortingEnabled = self.joint_table.isSortingEnabled()
        self.joint_table.setSortingEnabled(False)
        item = self.joint_table.item(0, 0)
        item.setText(_translate("MainWindow", "J1"))
        item = self.joint_table.item(0, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.joint_table.item(1, 0)
        item.setText(_translate("MainWindow", "J2"))
        item = self.joint_table.item(1, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.joint_table.item(2, 0)
        item.setText(_translate("MainWindow", "J3"))
        item = self.joint_table.item(2, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.joint_table.item(3, 0)
        item.setText(_translate("MainWindow", "J4"))
        item = self.joint_table.item(3, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.joint_table.item(4, 0)
        item.setText(_translate("MainWindow", "J5"))
        item = self.joint_table.item(4, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.joint_table.item(5, 0)
        item.setText(_translate("MainWindow", "J6"))
        item = self.joint_table.item(5, 1)
        item.setText(_translate("MainWindow", "-"))
        self.joint_table.setSortingEnabled(__sortingEnabled)
        item = self.cart_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "항목"))
        item = self.cart_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "값"))
        __sortingEnabled = self.cart_table.isSortingEnabled()
        self.cart_table.setSortingEnabled(False)
        item = self.cart_table.item(0, 0)
        item.setText(_translate("MainWindow", "X"))
        item = self.cart_table.item(0, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.cart_table.item(1, 0)
        item.setText(_translate("MainWindow", "Y"))
        item = self.cart_table.item(1, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.cart_table.item(2, 0)
        item.setText(_translate("MainWindow", "Z"))
        item = self.cart_table.item(2, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.cart_table.item(3, 0)
        item.setText(_translate("MainWindow", "A"))
        item = self.cart_table.item(3, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.cart_table.item(4, 0)
        item.setText(_translate("MainWindow", "B"))
        item = self.cart_table.item(4, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.cart_table.item(5, 0)
        item.setText(_translate("MainWindow", "C"))
        item = self.cart_table.item(5, 1)
        item.setText(_translate("MainWindow", "-"))
        self.cart_table.setSortingEnabled(__sortingEnabled)
        item = self.robot_state_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "항목"))
        item = self.robot_state_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "값"))
        __sortingEnabled = self.robot_state_table.isSortingEnabled()
        self.robot_state_table.setSortingEnabled(False)
        item = self.robot_state_table.item(0, 0)
        item.setText(_translate("MainWindow", "연결타입"))
        item = self.robot_state_table.item(0, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.robot_state_table.item(1, 0)
        item.setText(_translate("MainWindow", "통신상태"))
        item = self.robot_state_table.item(1, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.robot_state_table.item(2, 0)
        item.setText(_translate("MainWindow", "로봇상태"))
        item = self.robot_state_table.item(2, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.robot_state_table.item(3, 0)
        item.setText(_translate("MainWindow", "로봇모드"))
        item = self.robot_state_table.item(3, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.robot_state_table.item(4, 0)
        item.setText(_translate("MainWindow", "제어모드"))
        item = self.robot_state_table.item(4, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.robot_state_table.item(5, 0)
        item.setText(_translate("MainWindow", "작업상태"))
        item = self.robot_state_table.item(5, 1)
        item.setText(_translate("MainWindow", "-"))
        self.robot_state_table.setSortingEnabled(__sortingEnabled)
        self.robot_cycle_label.setText(_translate("MainWindow", "업데이트: - ms"))
        self.motion_group_title.setText(_translate("MainWindow", "기본 동작"))
        self.home_button.setText(_translate("MainWindow", "홈위치 무브"))
        self.pushButton.setText(_translate("MainWindow", "좌표계 무브"))
        self.reset_button.setText(_translate("MainWindow", "리셋"))
        self.print_pos_button.setText(_translate("MainWindow", "조인트 무브"))
        self.print_pos_button_2.setText(_translate("MainWindow", "모드변경"))
        self.home_button_2.setText(_translate("MainWindow", "홈위치 저장"))
        self.tool_change_button.setText(_translate("MainWindow", "툴 변경"))
        self.emergency_stop_button.setText(_translate("MainWindow", "정지"))
        self.gripper_move_button.setText(_translate("MainWindow", "그리퍼 이동"))
        self.gripper_stroke_input.setToolTip(_translate("MainWindow", "그리퍼 사이 거리 입력값 (mm)\n"
"허용 범위: 0.00 ~ 109.00"))
        self.gripper_stroke_input.setText(_translate("MainWindow", "60.0"))
        self.gripper_stroke_input.setPlaceholderText(_translate("MainWindow", "예: 35.5 (mm)"))
        self.gripper_range_value_label.setText(_translate("MainWindow", "허용 범위: 0.00 ~ 109.00 열림"))
        self.gripper_range_title_label.setText(_translate("MainWindow", "그리퍼 사이 거리 입력 (mm)"))
        self.vision_dialog_toggle_switch.setText(_translate("MainWindow", "비전 클릭이동"))
        self.vision_x_axis_label.setText(_translate("MainWindow", "X"))
        self.vision_y_axis_label.setText(_translate("MainWindow", "Y"))
        self.vision_z_axis_label.setText(_translate("MainWindow", "Z"))
        self.vision_x_margin_input.setToolTip(_translate("MainWindow", "비전 좌표 이동 시 적용할 X 옵셋 (mm)"))
        self.vision_x_margin_input.setText(_translate("MainWindow", "0.0"))
        self.vision_x_margin_input.setPlaceholderText(_translate("MainWindow", "X(mm)"))
        self.vision_y_margin_input.setToolTip(_translate("MainWindow", "비전 좌표 이동 시 적용할 Y 옵셋 (mm)"))
        self.vision_y_margin_input.setText(_translate("MainWindow", "0.0"))
        self.vision_y_margin_input.setPlaceholderText(_translate("MainWindow", "Y(mm)"))
        self.vision_z_margin_input.setToolTip(_translate("MainWindow", "비전 좌표 이동 시 적용할 Z 옵셋 (mm)"))
        self.vision_z_margin_input.setText(_translate("MainWindow", "0.0"))
        self.vision_z_margin_input.setPlaceholderText(_translate("MainWindow", "Z(mm)"))
        self.vision_move_button.setText(_translate("MainWindow", "비전 좌표 이동"))
        self.vision_z_range_label.setText(_translate("MainWindow", "허용 범위: -300.0 ~ 300.0"))
        self.vision_z_title_label.setText(_translate("MainWindow", "XYZ 옵셋 입력 (mm)"))
        self.vision_dialog_toggle_button.setText(_translate("MainWindow", "비전클릭이동 ON"))
        self.top_status_robot_text.setText(_translate("MainWindow", "로봇: 확인중"))
        self.top_status_robot_dot.setText(_translate("MainWindow", "●"))
        self.top_status_robot_toggle.setText(_translate("MainWindow", "ON"))
        self.current_tool_label.setText(_translate("MainWindow", "툴(TCP): -"))
        self.label_2.setText(_translate("MainWindow", "로그 "))
        self.log_clear_button.setText(_translate("MainWindow", "로그 클리어"))
        self.yolo_view_2.setText(_translate("MainWindow", "YOLO 화면 영역"))
        self.vision_cycle_label_2.setText(_translate("MainWindow", "업데이트: - ms"))
        self.vision_serial_label_2.setText(_translate("MainWindow", "시리얼: -"))
        self.vision_rotate_left_button_2.setText(_translate("MainWindow", "↺90"))
        self.vision_rotate_zero_button_2.setText(_translate("MainWindow", "0°"))
        self.vision_rotate_right_button_2.setText(_translate("MainWindow", "↻90"))
        self.vision_rotation_label_2.setText(_translate("MainWindow", "각도: 0°"))
        self.vision_serial_change_button_2.setText(_translate("MainWindow", "카메라 변경"))
        self.top_status_vision_dot_2.setText(_translate("MainWindow", "●"))
        self.top_status_vision_text_2.setText(_translate("MainWindow", "비전2: 확인중"))
        self.top_status_vision2_toggle.setText(_translate("MainWindow", "ON"))
        self.calibration_mode_switch_2.setText(_translate("MainWindow", "켈리브레이션활성화"))
        self.calibration_matrix_file_label_2.setText(_translate("MainWindow", "현재 적용행렬 : (없음)"))
        self.calibration_load_button_2.setText(_translate("MainWindow", "불러오기"))
        self.calibration_transform_button_2.setText(_translate("MainWindow", "비전<-> 로봇 좌표 켈리브레이션 시작"))
